### ISSUE TITLE
UNAUTH: Invalid nonce

### ISSUE THREAD

**Issue by MoXyLe** [sammchardy/python-kucoin#34]
Since today's morning I just keep getting this errors. For example, when I am trying to cancel order I have got this 
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    client.cancel_order(transaction['orderOid'], Client.SIDE_BUY, 'ETH-BTC')
  File "C:\Users\roofu\Desktop\Bot\myvenv\lib\site-packages\kucoin\client.py", line 1313, in cancel_order
    return self._post('cancel-order', True, data=data)
  File "C:\Users\roofu\Desktop\Bot\myvenv\lib\site-packages\kucoin\client.py", line 180, in _post
    return self._request('post', path, signed, **kwargs)
  File "C:\Users\roofu\Desktop\Bot\myvenv\lib\site-packages\kucoin\client.py", line 147, in _request
    return self._handle_response(response)
  File "C:\Users\roofu\Desktop\Bot\myvenv\lib\site-packages\kucoin\client.py", line 161, in _handle_response
    raise KucoinAPIException(response)
kucoin.exceptions.KucoinAPIException: KucoinAPIException UNAUTH: Invalid nonce
What's the reason of this error?

**Comment by MoXyLe** [comment]
It fixed by itself somehow
