### ISSUE TITLE
Unable to auth API 

### ISSUE THREAD

**Issue by noixez** [sammchardy/python-kucoin#35]
Hey Guys,

My bot has worked for a long time; however, in the past few weeks I haven't used it, ran it again and received an auth error, I've also updated my API key without success. 

Anyone have any idea whether there has been an update with the Kucoin API causing issues?

raceback (most recent call last):
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\tradingbot.py", line 34, in <module>
    option1.getbalance()
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\option1.py", line 12, in getbalance
    pprint.pprint(client.get_coin_balance('DENT'))
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\kucoin\client.py", line 944, in get_coin_balance
    return self._get('account/{}/balance'.format(coin), True)
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\kucoin\client.py", line 177, in _get
    return self._request('get', path, signed, **kwargs)
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\kucoin\client.py", line 147, in _request
    return self._handle_response(response)
  File "Z:\06. Programming Projects\00_02_CryptoBots\python-kucoin-develop\kucoin\client.py", line 161, in _handle_response
    raise KucoinAPIException(response)
kucoin.exceptions.KucoinAPIException: KucoinAPIException UNAUTH: Invalid API Key
Press any key to continue . . .

Regards
Chris

**Comment by sirspoon** [comment]
I think there's some tickboxes for permissions on kucoin for the keys. My
boy had a similar issue until I enabled all the tickboxes.

**Comment by noixez** [comment]
Interesting, I've ticked everything and changed a few keys now, still no luck, strange! What about IP white list? I had mine set on "No Limit"

I'm so confuised

**Comment by noixez** [comment]
Feel free to close, what's the issue?

My main .py file declared api_key and api_secret; however, I also included .py forms whereby I also declared the keys which overwrote my original.

Just a new programmer here, sorry guys!

**Comment by icehongssii** [comment]
I also have the same issue. 
`Traceback (most recent call last):
  File "t1.py", line 12, in <module>
    transaction = client.create_buy_order('KCS-BTC', '0.01', '1000')
  File "/Users/icehongssi/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kucoin/client.py", line 1134, in create_buy_order
    return self.create_order(symbol, self.SIDE_BUY, price, amount)
  File "/Users/icehongssi/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kucoin/client.py", line 1104, in create_order
    return self._post('order', True, data=data)
  File "/Users/icehongssi/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kucoin/client.py", line 180, in _post
    return self._request('post', path, signed, **kwargs)
  File "/Users/icehongssi/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kucoin/client.py", line 147, in _request
    return self._handle_response(response)
  File "/Users/icehongssi/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kucoin/client.py", line 161, in _handle_response
    raise KucoinAPIException(response)
kucoin.exceptions.KucoinAPIException: KucoinAPIException UNAUTH: No access authorization`

**Comment by sammchardy** [comment]
Closing because of new API version
